### ISSUE TITLE
i3lock.sh doesnt work

### ISSUE THREAD

**Issue by EliaHKM** [LRDPRDX/my-config#1]
Hi,
I like your i3lock customization  but it doesn't work for me
when I run it in the terminal it gives me  this message: 
`i3lock: unrecognized option '--insidevercolor=#21222cee'
i3lock: Syntax: i3lock [-v] [-n] [-b] [-d] [-c color] [-u] [-p win|default] [-i image.png] [-t] [-e] [-I timeout] [-f]`
what should I do to make it works?
I'm in Debain 10.9 buster.
Thanks in advance.

**Comment by LRDPRDX** [comment]
Hi, make sure you're using `i3lock-color` first. [Here](https://github.com/Raymo111/i3lock-color) is the project.

**Comment by EliaHKM** [comment]
Thank you so much.
It's working.

**Comment by LRDPRDX** [comment]
Gern geschehen :)
